### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by DaxSosa** [rockstardev/BTCPayServerPlugins.RockstarDev#20]
Could you create a way to delete a user, for example if they leave the company, even if they have already paid invoices?, or if you delete it, it forces you to download the entire invoice record

**Comment by TChukwuleta** [comment]
Sure @DaxSosa  the user deletion is already being worked on.

Regarding the second, "if you delete it, it forces you to download the entire invoice record", can you explain the requests.

If you delete a user, they wont have access to your payroll, so who is downloading the entire invoice record?

**Comment by DaxSosa** [comment]
Thank you, for the response, I explain, the administrator is obliged to download the entire payment history of the user before deleting it

**Comment by TChukwuleta** [comment]
alright. Got it.  Would look into that. Thank you

**Comment by rockstardev** [comment]
Hey @DaxSosa,

Based on our discussion I have opened issues #25 & #26. Now that we have deletion of users & disabling of user this should handle the case of person leaving employment fully.

So I will close this issue in favor of new issues where we are handling this functionality.

**Comment by DaxSosa** [comment]
Thanks
