### ISSUE TITLE
Download all invoices for certain user

### ISSUE THREAD

**Issue by rockstardev** [rockstardev/BTCPayServerPlugins.RockstarDev#25]
After discussion with Dax, he explained that it would be good to be able to download all the invoices for users that are let go for archival purposes. So, we should add this option in user menu. Illustration:

![image](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/assets/5191402/bf90a86c-b4bd-4731-9310-4eb456cd18d0)

**Comment by TChukwuleta** [comment]
Download as csv yea?. 


Basically using the information from each of the invoices as table headers yea?
