### ISSUE TITLE
Create a better icon for Payroll plugin

### ISSUE THREAD

**Issue by rockstardev** [rockstardev/BTCPayServerPlugins.RockstarDev#3]
Right now we are depending on the same icon for vouchers that @Kukks did, we need a better icon before launch.

Here it is how it looks now:
![image](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/assets/5191402/a5fe89a0-91c7-4f81-bb17-3572e3f819b2)

The file that needs to be updated:
https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/blob/master/Plugins/BTCPayServer.RockstarDev.Plugins.Payroll/Views/Shared/PayrollNav.cshtml#L17

**Comment by TChukwuleta** [comment]
![image](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/assets/47084273/dfee1f12-6008-494e-a344-54a57201d262)


![image](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/assets/47084273/229add5b-eb9e-417f-a226-1756a00abc76)


Does this work @rockstardev ?

**Comment by rockstardev** [comment]
@TChukwuleta nailed it!
