### ISSUE TITLE
[feat] setting to permit invoice creation without file attachement

### ISSUE THREAD

**Issue by MattDHill** [rockstardev/BTCPayServerPlugins.RockstarDev#38]
It would be nice to create a payroll invoice without needing to upload a file. For example, many real-world payouts take place without a formal invoices, for example an employee getting paid a set salary each month. If additional context is needed, often thje description field will suffice.

**Comment by rockstardev** [comment]
The best approach is to introduce a new Settings page:

![image](https://github.com/rockstardev/BTCPayServerPlugins.RockstarDev/assets/5191402/03e09e22-65a2-4dad-bbaf-87b56caff71d)

We should include a `Make Invoice Files Options` setting within the `PayrollPluginSettings`. 

Once user navigate to the Payroll Plugin Settings page, all the properties from that `PayrollPluginSettings` class should be editable. This will allow for more flexible and user-friendly configuration options.
